### ISSUE TITLE
external build fail

### ISSUE THREAD

**Issue by bobbySpace** [uelordi01/openface-android-sample#1]
Build command failed.
Error while executing process /Users/bobby/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app -B/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/.externalNativeBuild/cmake/debug/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/build/intermediates/cmake/debug/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/bobby/android/android-ndk-r14b -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_TOOLCHAIN_FILE=/Users/bobby/android/android-ndk-r14b/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/bobby/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DOpenCV_DIR=/Users/bobby/ar/OpenCV-android-sdk/sdk/native/jni -Ddlib_DIR=/Users/bobby/ar/dlib-19.7/dlib -DANDROID_NATIVE_API_LEVEL=23 -DANDROID_CPP_FEATURES=rtti exceptions -DANDROID_STL=gnustl_static -DDLIB_ENABLE_ASSERTS=OFF -DDLIB_NO_GUI_SUPPORT=ON -DDLIB_JPEG_SUPPORT=OFF -DDLIB_PNG_SUPPORT=OFF -DDLIB_LINK_WITH_SQLITE3=OFF}
-- Check for working C compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
    /Users/bobby/ar/OpenCV-android-sdk/sdk/native/jni/OpenCVModules_arm64_v8a.cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (FIND_PACKAGE)
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Searching for BLAS and LAPACK
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
source /Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectionValidator.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorFunc.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorModel.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorParameters.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/PAW.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/PDM.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/Patch_experts.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/SVR_patch_expert.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/stdafx.cpp 
-- Configuring incomplete, errors occurred!
See also "/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/.externalNativeBuild/cmake/debug/arm64-v8a/CMakeFiles/CMakeOutput.log".
Build command failed.
Error while executing process /Users/bobby/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app -B/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/.externalNativeBuild/cmake/release/arm64-v8a -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/build/intermediates/cmake/release/obj/arm64-v8a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/Users/bobby/android/android-ndk-r14b -DCMAKE_CXX_FLAGS=-std=c++14 -DCMAKE_TOOLCHAIN_FILE=/Users/bobby/android/android-ndk-r14b/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/bobby/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DOpenCV_DIR=/Users/bobby/ar/OpenCV-android-sdk/sdk/native/jni -Ddlib_DIR=/Users/bobby/ar/dlib-19.7/dlib -DANDROID_NATIVE_API_LEVEL=23 -DANDROID_CPP_FEATURES=rtti exceptions -DANDROID_STL=gnustl_static -DDLIB_ENABLE_ASSERTS=OFF -DDLIB_NO_GUI_SUPPORT=ON -DDLIB_JPEG_SUPPORT=OFF -DDLIB_PNG_SUPPORT=OFF -DDLIB_LINK_WITH_SQLITE3=OFF}
-- Check for working C compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang
-- Check for working C compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++
-- Check for working CXX compiler: /Users/bobby/android/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
    /Users/bobby/ar/OpenCV-android-sdk/sdk/native/jni/OpenCVModules_arm64_v8a.cmake
Call Stack (most recent call first):
  CMakeLists.txt:5 (FIND_PACKAGE)
-- Building a C++11 test project to see if your compiler supports C++11
-- C++11 activated.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Searching for BLAS and LAPACK
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
 *****************************************************************************
 *** No BLAS library found so using dlib's built in BLAS.  However, if you ***
 *** install an optimized BLAS such as OpenBLAS or the Intel MKL your code ***
 *** will run faster.  On Ubuntu you can install OpenBLAS by executing:    ***
 ***    sudo apt-get install libopenblas-dev liblapack-dev                 ***
 *** Or you can easily install OpenBLAS from source by downloading the     ***
 *** source tar file from http://www.openblas.net, extracting it, and      ***
 *** running:                                                              ***
 ***    make; sudo make install                                            ***
 *****************************************************************************
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.5")
-- *** cuDNN V5.0 OR GREATER NOT FOUND.  DLIB WILL NOT USE CUDA. ***
-- *** If you have cuDNN then set CMAKE_PREFIX_PATH to include cuDNN's folder.
source /Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/CCNF_patch_expert.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectionValidator.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorFunc.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorModel.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/L-- Configuring incomplete, errors occurred!
andmarkDetectorParameters.cpp;/Users/bobby/ar/openface-andrSee also "/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/.externalNativeBuild/cmake/release/arm64-v8a/CMakeFiles/CMakeOutput.log".
oid-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/LandmarkDetectorUtils.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/PAW.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/PDM.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/Patch_experts.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/SVR_patch_expert.cpp;/Users/bobby/ar/openface-android-sample-master/OpenFaceDemo/app/../../Openface_reduced/lib/local/LandmarkDetector/src/stdafx.cpp

**Comment by uelordi01** [comment]
Sorry but I can not see where is the error.
maybe if you look the CMakeOutput log you will see the error.
If you put the the dlib library correctly in the local. properties. 

The sample is not complete yet, we are still developing the features of the openface.
